services:
  db:
    container_name: db
    image: mariadb:11.1
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'ln -s /usr/bin/mariadb /usr/bin/mysql && mysql -umysqluser -p"this is the sql user pw" zm --execute="SELECT count(Id) > 0 FROM Users;" --skip-column-names -B']
      interval: 3s
      timeout: 3s
      retries: 4
    networks:
      - zoneminder
    ports:
      - 3307:3306
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /ethereum/security/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zm
    env_file:
      - ./.env

  zoneminder:
    container_name: zoneminder
    image: zm_eventserver:49
    restart: always
    stop_grace_period: 45s
    healthcheck:
      test: ["CMD-SHELL", "service nginx status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      - db
    ports:
      - 1080:80
      - 444:443
      - 9000:9000
    networks:
      - zoneminder
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /ethereum/security/data:/data
      - /ethereum/security/log:/log
      - ./config:/config
      - ./data/nginx:/etc/nginx/conf.d
      - ./sounds:/var/www/html/sounds
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1000000000
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    env_file:
      - ./.env

networks:
  zoneminder:
